/*
Pentagon numbers

Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k − P_j| is minimised; what is the value of D?

https://projecteuler.net/problem=44

The preceding problem was taken from Project Euler and is under a Creative Commons Licence:
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
This does not apply to the solution/code.
*/

export default function problem44(n = 1) {
    while (true) { // Scary
        let num = n * (3 * n - 1) / 2;
        let val1 = Math.ceil((num + 2) / 3) + 1;
        while (val1 > 0) {
            let val2 = val1 - 1;
            let num1 = val1 * (3 * val1 - 1) / 2;
            while (val2 > 0) {
                let num2 = val2 * (3 * val2 - 1) / 2;
                if (num1 - num2 > num) // Too lazy to find a better method
                    break;
                if (num1 - num2 == num && Number.isInteger((Math.sqrt(24 * (num1 + num2) + 1) + 1) / 6))
                    return num;
                val2--;
            }
            val1--;
        }
        n++;
    }
}
