/*
Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	T_n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	P_n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	H_n=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

https://projecteuler.net/problem=45

The preceding problem was taken from Project Euler and is under a Creative Commons Licence:
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
This does not apply to the solution/code.
*/

export default function problem45(n = 144) {
    let val = n * (2 * n - 1);
    while ((Math.sqrt(1 + 8 * val) - 1) % 2 != 0 || (Math.sqrt(1 + 24 * val) + 1) % 6 != 0)
        val += 4 * n + 1,
        ++n;
    return val;
}